In [1]:
import numpy as np


In [2]:
a=np.array([1,2,3])

In [3]:
a

array([1, 2, 3])

In [4]:
type(a)

numpy.ndarray

In [5]:
np.shape(a)

(3,)

In [8]:
b=np.array([[1,2],[3,4]])


In [9]:
print(b)

[[1 2]
 [3 4]]


In [10]:
np.shape(b)

(2, 2)

In [11]:
b[1]

array([3, 4])

In [12]:
b[1][1]

4

In [13]:
b[1,1]

4

In [15]:
c=np.zeros((3,4))

In [16]:
c

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [17]:
d=np.full((3,3),2)

In [18]:
d

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [19]:
e=np.random.random((3,3))

In [20]:
e

array([[0.29385726, 0.09880885, 0.0100332 ],
       [0.41386322, 0.63265512, 0.24211336],
       [0.94703073, 0.0081231 , 0.3016546 ]])

In [21]:
h=np.array([[1,2,3,4],[5,6,7,8]])

In [22]:
h

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [23]:
i=h[:2,1:3]

In [24]:
i

array([[2, 3],
       [6, 7]])

In [36]:
i[0,0]=500

In [37]:
i

array([[500,   3],
       [  6,   7]])

In [38]:
h#we modified our original array by modifying just i

array([[  1, 500,   3,   4],
       [  5,   6,   7,   8]])

In [39]:
h.dtype#gives dataype of inner values of h

dtype('int32')

In [40]:
l=np.array([1.1,2])

In [41]:
l

array([1.1, 2. ])

In [42]:
l.dtype#array contain single datatype values,not mixed ones

dtype('float64')

In [46]:
j=np.array([1.0,2.0],dtype=np.int32)#forcing datatype

In [47]:
j.dtype

dtype('int32')

In [48]:
j

array([1, 2])

In [51]:
a=np.array([[1.1,2.1],[2.3,5.4]],dtype=np.int32)

In [52]:
a

array([[1, 2],
       [2, 5]])

In [55]:
b=np.array([[2,2],[5,5.4]],dtype=np.int32)

In [56]:
b

array([[2, 2],
       [5, 5]])

In [64]:
print(a+b)
print(a-b)
print(a*b)

[[ 3  4]
 [ 7 10]]
[[-1  0]
 [-3  0]]
[[ 2  4]
 [10 25]]


In [65]:
a*b

array([[ 2,  4],
       [10, 25]])

In [66]:
a+b

array([[ 3,  4],
       [ 7, 10]])

In [67]:
np.sum(a)

10

In [71]:
b

array([[2, 2],
       [5, 5]])

In [74]:
np.sum(b,axis=0)#sum of rows

array([7, 7])

In [75]:
np.sum(b,axis=1)#sum of coumns

array([ 4, 10])