In [1]:
import numpy as np

In [2]:
l=[i for i in range(10)]

In [3]:
l

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [4]:
np.mean(l)

4.5

In [5]:
np.array(l)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
a=np.array(l)

In [7]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
type(a)

numpy.ndarray

In [9]:
np.mean(a)

4.5

In [10]:
import pandas as pd

In [40]:
url='F:\Desktop\Data_Preprocessing\Data.csv'

In [41]:
df=pd.read_csv(url)

In [42]:
type(df)

pandas.core.frame.DataFrame

In [60]:
df

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [61]:
lst=['batman','superman','wonder woman','Aquaman']
df1=pd.DataFrame(lst)

In [62]:
df1

0
0        batman
1      superman
2  wonder woman
3       Aquaman

In [63]:
lst1={'super_name':['batman','clark':'superman','Diana':'wonder woman','Arthur':'Aquaman'}
df11=pd.DataFrame(lst1)

Jupyter Notebook
Untitled4 Current Kernel Logo 

Python 3

    File
    Edit
    View
    Insert
    Cell
    Kernel
    Widgets
    Help

import numpy as np

l=[i for i in range(10)]

l

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

np.mean(l)

4.5

np.array(l)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

a=np.array(l)

a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

type(a)

numpy.ndarray

np.mean(a)

4.5

import pandas as pd

url='F:\Desktop\Data_Preprocessing\Data.csv'

df=pd.read_csv(url)

type(df)

pandas.core.frame.DataFrame

df

	Country 	Age 	Salary 	Purchased
0 	France 	44.0 	72000.0 	No
1 	Spain 	27.0 	48000.0 	Yes
2 	Germany 	30.0 	54000.0 	No
3 	Spain 	38.0 	61000.0 	No
4 	Germany 	40.0 	NaN 	Yes
5 	France 	35.0 	58000.0 	Yes
6 	Spain 	NaN 	52000.0 	No
7 	France 	48.0 	79000.0 	Yes
8 	Germany 	50.0 	83000.0 	No
9 	France 	37.0 	67000.0 	Yes

lst=['batman','superman','wonder woman','Aquaman']

df1=pd.DataFrame(lst)

df1

	0
0 	batman
1 	superman
2 	wonder woman
3 	Aquaman

lst1={'super_name':['batman','clark':'superman','Diana':'wonder woman','Arthur':'Aquaman'}

df11=pd.DataFrame(lst1)

  File "<ipython-input-57-98

SyntaxError: invalid syntax (<ipython-input-63-079613d01086>, line 1)

In [64]:
df11

super_name
0        batman
1      superman
2  wonder woman
3       Aquaman

In [65]:
type(df11)

pandas.core.frame.DataFrame

In [66]:
alias_lst=['Bruce','Clark','Diana','Arthur']
k=dict(zip(lst,alias_lst))

In [67]:
k

{'batman': 'Bruce',
 'superman': 'Clark',
 'wonder woman': 'Diana',
 'Aquaman': 'Arthur'}

In [68]:
df2=pd.DataFrame(k)

ValueError: If using all scalar values, you must pass an index

In [69]:
data={'Marvel':['spiderman','logan','Deadpool','Iron man']
     ,'DC':['Flash','Superman','Deathstroke','Batman']}

In [70]:
df2=pd.DataFrame(data)

In [71]:
df2

Marvel           DC
0  spiderman        Flash
1      logan     Superman
2   Deadpool  Deathstroke
3   Iron man       Batman

In [72]:
data = {'Name':['Jai', 'Princi', 'Gaurav', 'Anuj'],
        'Age':[27, 24, 22, 32],
        'Address':['Delhi', 'Kanpur', 'Allahabad', 'Kannauj'],
        'Qualification':['Msc', 'MA', 'MCA', 'Phd']}

In [73]:
df3=pd.DataFrame(data)

In [74]:
df3

Name  Age    Address Qualification
0     Jai   27      Delhi           Msc
1  Princi   24     Kanpur            MA
2  Gaurav   22  Allahabad           MCA
3    Anuj   32    Kannauj           Phd

In [75]:
df3[['Name','Address']]

Name    Address
0     Jai      Delhi
1  Princi     Kanpur
2  Gaurav  Allahabad
3    Anuj    Kannauj

In [76]:
data['Name']

['Jai', 'Princi', 'Gaurav', 'Anuj']

In [44]:
first=df.loc[0]

In [45]:
first

Country      France
Age              44
Salary        72000
Purchased        No
Name: 0, dtype: object

In [80]:
df

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [48]:
ninth=df.loc[4]

In [49]:
ninth

Country      Germany
Age               40
Salary           NaN
Purchased        Yes
Name: 4, dtype: object

In [77]:
df3

Name  Age    Address Qualification
0     Jai   27      Delhi           Msc
1  Princi   24     Kanpur            MA
2  Gaurav   22  Allahabad           MCA
3    Anuj   32    Kannauj           Phd

In [81]:
print(df.iloc[:])

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes


In [99]:
sal=pd.read_csv('F:\Desktop\ML-From-Scrach-master\Salary_Data.csv',index_col='YearsExperience')

In [100]:
k=sal['Salary']

In [101]:
k

YearsExperience
1.1      39343.0
1.3      46205.0
1.5      37731.0
2.0      43525.0
2.2      39891.0
2.9      56642.0
3.0      60150.0
3.2      54445.0
3.2      64445.0
3.7      57189.0
3.9      63218.0
4.0      55794.0
4.0      56957.0
4.1      57081.0
4.5      61111.0
4.9      67938.0
5.1      66029.0
5.3      83088.0
5.9      81363.0
6.0      93940.0
6.8      91738.0
7.1      98273.0
7.9     101302.0
8.2     113812.0
8.7     109431.0
9.0     105582.0
9.5     116969.0
9.6     112635.0
10.3    122391.0
10.5    121872.0
Name: Salary, dtype: float64

In [102]:
j=sal.loc[10.3]

In [103]:
j

Salary    122391.0
Name: 10.3, dtype: float64

In [111]:
sal=pd.read_csv('F:\Desktop\ML-From-Scrach-master\Salary_Data.csv')

In [107]:
sal

YearsExperience    Salary
0               1.1   39343.0
1               1.3   46205.0
2               1.5   37731.0
3               2.0   43525.0
4               2.2   39891.0
5               2.9   56642.0
6               3.0   60150.0
7               3.2   54445.0
8               3.2   64445.0
9               3.7   57189.0
10              3.9   63218.0
11              4.0   55794.0
12              4.0   56957.0
13              4.1   57081.0
14              4.5   61111.0
15              4.9   67938.0
16              5.1   66029.0
17              5.3   83088.0
18              5.9   81363.0
19              6.0   93940.0
20              6.8   91738.0
21              7.1   98273.0
22              7.9  101302.0
23              8.2  113812.0
24              8.7  109431.0
25              9.0  105582.0
26              9.5  116969.0
27              9.6  112635.0
28             10.3  122391.0
29             10.5  121872.0

In [108]:
l=sal.loc[27]

In [109]:
l

YearsExperience         9.6
Salary             112635.0
Name: 27, dtype: float64

In [114]:
b=sal.iloc[:2]

In [115]:
b

YearsExperience   Salary
0              1.1  39343.0
1              1.3  46205.0

In [116]:
sal.columns

Index(['YearsExperience', 'Salary'], dtype='object')

In [118]:
sal.row

AttributeError: 'DataFrame' object has no attribute 'row'

In [119]:
df

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [126]:
df.loc[:5,['Country','Age']]

Country   Age
0   France  44.0
1    Spain  27.0
2  Germany  30.0
3    Spain  38.0
4  Germany  40.0
5   France  35.0

In [127]:
df.loc[5:,['Country','Age']]

Country   Age
5   France  35.0
6    Spain   NaN
7   France  48.0
8  Germany  50.0
9   France  37.0

In [131]:
df.loc[5:9]

Country   Age   Salary Purchased
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [132]:
df.loc[5:9,'Country']

5     France
6      Spain
7     France
8    Germany
9     France
Name: Country, dtype: object

In [135]:
df.iloc[:5,0:3]

Country   Age   Salary
0   France  44.0  72000.0
1    Spain  27.0  48000.0
2  Germany  30.0  54000.0
3    Spain  38.0  61000.0
4  Germany  40.0      NaN

In [136]:
df.dtypes

Country       object
Age          float64
Salary       float64
Purchased     object
dtype: object

In [137]:
df.Country.unique()

array(['France', 'Spain', 'Germany'], dtype=object)

In [138]:
df.Age.unique()

array([44., 27., 30., 38., 40., 35., nan, 48., 50., 37.])

In [141]:
df.groupby(['Country','Age']).size()

Country  Age 
France   35.0    1
         37.0    1
         44.0    1
         48.0    1
Germany  30.0    1
         40.0    1
         50.0    1
Spain    27.0    1
         38.0    1
dtype: int64

In [142]:
import numpy as np

In [144]:
a=np.array([[1,2],[3,4]])

In [145]:
a

array([[1, 2],
       [3, 4]])

In [146]:
b = np.array([[11,12],[13,14]])

In [147]:
np.dot(a,b)

array([[37, 40],
       [85, 92]])

In [151]:
import pandas as pd
url = "nhanes_2015_2016.csv"
da = pd.read_csv(url)

FileNotFoundError: [Errno 2] File b'nhanes_2015_2016.csv' does not exist: b'nhanes_2015_2016.csv'

In [152]:
da=pd.read_csv(url)

FileNotFoundError: [Errno 2] File b'nhanes_2015_2016.csv' does not exist: b'nhanes_2015_2016.csv'

In [153]:
df


Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [156]:
df.iloc[:,0:2]

Country   Age
0   France  44.0
1    Spain  27.0
2  Germany  30.0
3    Spain  38.0
4  Germany  40.0
5   France  35.0
6    Spain   NaN
7   France  48.0
8  Germany  50.0
9   France  37.0

In [157]:
df

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [159]:
df.iloc[:5,1:4]

Age   Salary Purchased
0  44.0  72000.0        No
1  27.0  48000.0       Yes
2  30.0  54000.0        No
3  38.0  61000.0        No
4  40.0      NaN       Yes

In [160]:
x = df.iloc[3, :]

In [161]:
x

Country      Spain
Age             38
Salary       61000
Purchased       No
Name: 3, dtype: object

In [162]:
df.Age

0    44.0
1    27.0
2    30.0
3    38.0
4    40.0
5    35.0
6     NaN
7    48.0
8    50.0
9    37.0
Name: Age, dtype: float64