In [212]:
import numpy as np
a=np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]],dtype='int32')

In [213]:
print(a)

[[9 8 7]
 [6 5 4]]


In [214]:
#Get Dimension
a.ndim

2

In [215]:
a.shape

(2, 3)

In [216]:
#Get Type
type(a)
a.dtype

dtype('int32')

In [217]:
a.itemsize

4

In [218]:
#Get Total Size
a.size*a.itemsize

24

In [219]:
#Get Total Size
a.nbytes

24

In [220]:
a=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])

In [221]:
a[1,1]

9

In [222]:
a[-1,-1]       #Negative indexing

14

In [223]:
a[0,:]  #1st row all columns

array([1, 2, 3, 4, 5, 6, 7])

In [224]:
a[:,2]    #specific column

array([ 3, 10])

In [225]:
a[0,1:6:2]   #Jump of 2

array([2, 4, 6])

In [226]:
a[1,2]=67

In [227]:
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 67, 11, 12, 13, 14]])

In [228]:
a[:,6]=78

In [229]:
a

array([[ 1,  2,  3,  4,  5,  6, 78],
       [ 8,  9, 67, 11, 12, 13, 78]])

In [230]:
a[:,5]=1,2  #value assigning

In [231]:
a

array([[ 1,  2,  3,  4,  5,  1, 78],
       [ 8,  9, 67, 11, 12,  2, 78]])

In [232]:
b=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

In [233]:
b

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [234]:
b.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8])

In [235]:
b

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [236]:
b[1,1,1]

8

In [237]:
b[0,1,1]   #to get 4

4

In [238]:
b

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [242]:
b[:,1,:]

array([[9, 8],
       [6, 4]])

In [243]:
b.mean()

5.125

In [244]:
b[:,1,:]=[[9,8],[6,4]]

In [245]:
b

array([[[1, 2],
        [9, 8]],

       [[5, 6],
        [6, 4]]])

In [246]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [247]:
np.zeros((2,2,3))

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [248]:
np.zeros((2,2,3,2))

array([[[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]]])

In [249]:
np.ones((4,3,3),dtype='int32')

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]])

In [250]:
#Any Number
np.full((2,3),45)

array([[45, 45, 45],
       [45, 45, 45]])

In [251]:
np.full(a.shape,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [252]:
np.full_like(a,5)

array([[5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5]])

In [253]:
np.random.rand(4,2,3)

array([[[0.31273162, 0.66006702, 0.36731845],
        [0.70035315, 0.21269417, 0.81646912]],

       [[0.04501496, 0.19870542, 0.98156313],
        [0.20470377, 0.36737687, 0.43231836]],

       [[0.45124584, 0.45633994, 0.38121826],
        [0.38357558, 0.46997554, 0.12017274]],

       [[0.42040961, 0.67739964, 0.64750223],
        [0.30505845, 0.98804178, 0.82944826]]])

In [254]:
np.random.random_sample(a.shape)

array([[0.07924624, 0.47076756, 0.43229279, 0.51065779, 0.1870172 ,
        0.00639524, 0.11461823],
       [0.49376197, 0.0378034 , 0.7079719 , 0.13934384, 0.51833148,
        0.30575435, 0.03835928]])

In [255]:
#Random Integer Values,starting value,ending value, size
np.random.randint(-40,99,size=(3,3))

array([[ 52,  47,  13],
       [-17, -25,  54],
       [  5,  62, -32]])

In [258]:
#The Identity Matrix
np.identity(3,dtype='int8')

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int8)

In [259]:
#Repeat 
arr=np.array([[1,2,3]])
r1=np.repeat(arr,3,axis=0)   #axis=0 is the axis along the row
r1

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [260]:
ar=np.array([[1],[2],[3]])
r2=np.repeat(ar,3,axis=1)   #axis=1 is the axis along the columns
r2

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [261]:
ar=np.array([[1],[2],[3]])
r2=np.repeat(ar,3,axis=0)
r2

array([[1],
       [1],
       [1],
       [2],
       [2],
       [2],
       [3],
       [3],
       [3]])

In [266]:
k=np.arange(6)      #np.arange(6) is equivalent to np.array([0,1,2,3,4,5])
k

array([0, 1, 2, 3, 4, 5])

In [267]:
j=np.reshape(k,(2,3))
j

array([[0, 1, 2],
       [3, 4, 5]])

In [268]:
np.sum(j,axis=0)  # When we set axis = 0,  we collapse the rows … we collapse axis 0.

array([3, 5, 7])

In [265]:
np.sum(j,axis=1)  #when we set axis=1,we collapse the axis 1

array([ 3, 12])

In [269]:
a=np.arange(9)
a=np.reshape(a,(3,3))

In [270]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [271]:
b=np.arange(10,19)

In [275]:
b=np.reshape(b,(3,3))

In [276]:
b

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [277]:
c=np.concatenate((a,b),axis=0)

In [278]:
print(c)
print(c.shape)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [10 11 12]
 [13 14 15]
 [16 17 18]]
(6, 3)


In [279]:
d=np.concatenate((a,b),axis=1)

In [98]:
print(d)
print(d.shape)

[[ 0  1  2 10 11 12]
 [ 3  4  5 13 14 15]
 [ 6  7  8 16 17 18]]
(3, 6)


In [102]:
np.sum(d,axis=0) #collapses around axis 0

array([ 9, 12, 15, 39, 42, 45])

In [103]:
np.sum(d)   #collapses whole array

162

In [113]:
a=np.zeros((5,5),dtype='int32')

In [114]:
a

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [115]:
a[:,0]=1

In [117]:
a[:,4]=1

In [118]:
a[0,:]=1

In [119]:
a[4,:]=1

In [121]:
a[2,2]=9

In [122]:
print(a)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


# Be Careful while copying array

In [124]:
a=np.array([1,2,3])
b=a
b[0]=100
print(a)

[100   2   3]


# Use copy Instead direct assignment

In [128]:
a=np.arange(1,4)
print(a)
b=np.copy(a)  # or copy a by using a.copy()
b[0]=100
print(a)
print(b)

[1 2 3]
[1 2 3]
[100   2   3]


In [129]:
a=np.array([1,2,3,4])

In [130]:
a

array([1, 2, 3, 4])

In [138]:
a+2   #while adding to array,no error

array([3, 4, 5, 6])

In [139]:
a-2

array([-1,  0,  1,  2])

In [140]:
l=[1,2,3,4]

In [141]:
l+1  #while adding to list,error

TypeError: can only concatenate list (not "int") to list

In [142]:
a**2

array([ 1,  4,  9, 16], dtype=int32)

In [143]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [145]:
a=np.random.randint(1,9,(2,2))

In [146]:
a

array([[6, 2],
       [4, 5]])

In [149]:
b=np.identity(2,dtype='int32')

In [150]:
b

array([[1, 0],
       [0, 1]])

In [152]:
np.dot(a,b)

array([[6, 2],
       [4, 5]])

In [153]:
a*b

array([[6, 0],
       [0, 5]])

In [155]:
np.matmul(a,b)      #Matrix Multiplication

array([[6, 2],
       [4, 5]])

In [156]:
np.linalg.det(a)

22.000000000000004

In [157]:
np.linalg.det(b)

1.0

# statistics

In [160]:
a=np.arange(9)
a=np.reshape(a,(3,3))

In [161]:
np.mean(a,axis=0)

array([3., 4., 5.])

In [162]:
np.max(a,axis=0)

array([6, 7, 8])

In [163]:
np.max(a,axis=1)

array([2, 5, 8])

# Reshaping Array

In [173]:
#vertically stacking vectors
v1=np.arange(1,5)
v2=np.arange(5,9)
c=np.vstack([v1,v2])  #np.vstack((v1,v2))

In [174]:
np.vstack((v1,v2,v1,v2,v2,v1))

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8],
       [1, 2, 3, 4]])

In [175]:
np.hstack((v1,v2))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [182]:
np.hstack((c,np.concatenate((v1,v2),axis=0).reshape(2,4)))

array([[1, 2, 3, 4, 1, 2, 3, 4],
       [5, 6, 7, 8, 5, 6, 7, 8]])

# If for any reason you dont want to use pandas(hahaha),taking 
# files into  numpy array is done below

In [186]:
filedata=np.genfromtxt('F:\Desktop\mlr09.csv',delimiter=',')

In [187]:
filedata.astype('int32')

array([[-2147483648, -2147483648, -2147483648, -2147483648, -2147483648],
       [          6,         225,           0,           0,           9],
       [          6,         180,           0,           0,          11],
       [          6,         190,           0,           0,          15],
       [          6,         180,           0,           0,           8],
       [          6,         205,           0,           0,          23],
       [          6,         225,           0,           0,          27],
       [          6,         185,           0,           0,           9],
       [          6,         235,           0,           0,          16],
       [          6,         235,           0,           0,           4],
       [          6,         210,           0,           0,          12],
       [          6,         245,           0,           0,          20],
       [          6,         245,           0,           0,           9],
       [          6,         185,     

## Advanced Indexing and Boolean Masking

In [188]:
filedata>5

C:\Users\HP\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in greater
  """Entry point for launching an IPython kernel.


array([[False, False, False, False, False],
       [ True,  True, False, False,  True],
       [ True,  True, False, False,  True],
       [ True,  True, False, False,  True],
       [ True,  True, False, False,  True],
       [ True,  True, False, False,  True],
       [ True,  True, False, False,  True],
       [ True,  True, False, False,  True],
       [ True,  True, False, False,  True],
       [ True,  True, False, False, False],
       [ True,  True, False, False,  True],
       [ True,  True, False, False,  True],
       [ True,  True, False, False,  True],
       [ True,  True, False, False,  True],
       [ True,  True, False, False,  True],
       [ True,  True, False, False,  True],
       [ True,  True, False, False,  True],
       [ True,  True, False, False,  True],
       [ True,  True, False, False, False],
       [ True,  True, False, False,  True],
       [ True,  True, False, False,  True],
       [ True,  True, False, False,  True],
       [ True,  True, False, Fal

In [195]:
filedata[filedata<10]

C:\Users\HP\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in less
  """Entry point for launching an IPython kernel.


array([6.8  , 0.442, 0.672, 9.2  , 6.3  , 0.435, 0.797, 6.4  , 0.456,
       0.761, 6.2  , 0.416, 0.651, 8.6  , 6.9  , 0.449, 0.9  , 6.4  ,
       0.431, 0.78 , 6.3  , 0.487, 0.771, 9.3  , 6.8  , 0.469, 0.75 ,
       6.9  , 0.435, 0.818, 4.7  , 6.7  , 0.48 , 0.825, 6.9  , 0.516,
       0.632, 6.9  , 0.493, 0.757, 9.1  , 6.3  , 0.374, 0.709, 8.1  ,
       6.1  , 0.424, 0.782, 8.6  , 6.2  , 0.441, 0.775, 6.8  , 0.503,
       0.88 , 6.5  , 0.503, 0.833, 7.6  , 0.425, 0.571, 3.3  , 6.3  ,
       0.371, 0.816, 7.1  , 0.504, 0.714, 6.8  , 0.4  , 0.765, 7.3  ,
       0.482, 0.655, 7.2  , 6.4  , 0.475, 0.244, 6.8  , 0.428, 0.728,
       9.   , 7.2  , 0.559, 0.721, 6.4  , 0.441, 0.757, 6.6  , 0.492,
       0.747, 5.6  , 6.8  , 0.402, 0.739, 8.7  , 6.1  , 0.415, 0.713,
       7.7  , 6.5  , 0.492, 0.742, 6.4  , 0.484, 0.861, 6.   , 0.387,
       0.721, 7.7  , 6.   , 0.436, 0.785, 9.6  , 7.3  , 0.482, 0.655,
       7.2  , 6.1  , 0.34 , 0.821, 6.7  , 0.516, 0.728, 8.9  , 6.4  ,
       0.475, 0.846,

### you can index with a list in Numpy

In [196]:
a=np.array([1,2,3,4,5,6,7,8,9])

In [197]:
a[[1,2,8]]

array([2, 3, 9])

In [201]:
np.any(filedata>10,axis=0)

C:\Users\HP\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in greater
  """Entry point for launching an IPython kernel.


array([False,  True, False, False,  True])

In [202]:
np.any(filedata<10,axis=0)

C:\Users\HP\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in less
  """Entry point for launching an IPython kernel.


array([ True, False,  True,  True,  True])

In [203]:
filedata

array([[     nan,      nan,      nan,      nan,      nan],
       [6.80e+00, 2.25e+02, 4.42e-01, 6.72e-01, 9.20e+00],
       [6.30e+00, 1.80e+02, 4.35e-01, 7.97e-01, 1.17e+01],
       [6.40e+00, 1.90e+02, 4.56e-01, 7.61e-01, 1.58e+01],
       [6.20e+00, 1.80e+02, 4.16e-01, 6.51e-01, 8.60e+00],
       [6.90e+00, 2.05e+02, 4.49e-01, 9.00e-01, 2.32e+01],
       [6.40e+00, 2.25e+02, 4.31e-01, 7.80e-01, 2.74e+01],
       [6.30e+00, 1.85e+02, 4.87e-01, 7.71e-01, 9.30e+00],
       [6.80e+00, 2.35e+02, 4.69e-01, 7.50e-01, 1.60e+01],
       [6.90e+00, 2.35e+02, 4.35e-01, 8.18e-01, 4.70e+00],
       [6.70e+00, 2.10e+02, 4.80e-01, 8.25e-01, 1.25e+01],
       [6.90e+00, 2.45e+02, 5.16e-01, 6.32e-01, 2.01e+01],
       [6.90e+00, 2.45e+02, 4.93e-01, 7.57e-01, 9.10e+00],
       [6.30e+00, 1.85e+02, 3.74e-01, 7.09e-01, 8.10e+00],
       [6.10e+00, 1.85e+02, 4.24e-01, 7.82e-01, 8.60e+00],
       [6.20e+00, 1.80e+02, 4.41e-01, 7.75e-01, 2.03e+01],
       [6.80e+00, 2.20e+02, 5.03e-01, 8.80e-01, 2.50e+01

In [205]:
k=np.random.randint(-100,100,size=(6,5))
k

array([[ 81,  44,  38,  63,  58],
       [ 43,  28,  23, -37,  11],
       [-50, -19,  13, -60,  62],
       [  9,  35,  77,   0, -15],
       [ 52,  92,   0,  83, -76],
       [-75, -26, -59,  -9, -74]])

In [206]:
k[2:4,0:2]

array([[-50, -19],
       [  9,  35]])

In [210]:
k[[0,1,2,3],[1,2,3,4]]   #COOL ,AIN'T IT

array([ 44,  23, -60, -15])

In [211]:
k[[0,-2,-1],3:]

array([[ 63,  58],
       [ 83, -76],
       [ -9, -74]])